<a href="https://colab.research.google.com/github/ANAMMR1998/Fundamentos-programacion-AnaMariaMontealegre/blob/main/Entrega_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install ucimlrepo -q

In [ ]:


from ucimlrepo import fetch_ucirepo
import pandas as pd

student_performance = fetch_ucirepo(id=320)

X = student_performance.data.features
y = student_performance.data.targets

df = pd.concat([X, y], axis=1)
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [ ]:
print(student_performance.variables)

          name     role         type      demographic  \
0       school  Feature  Categorical             None
1          sex  Feature       Binary              Sex
2          age  Feature      Integer              Age
3      address  Feature  Categorical             None
4      famsize  Feature  Categorical            Other
5      Pstatus  Feature  Categorical            Other
6         Medu  Feature      Integer  Education Level
7         Fedu  Feature      Integer  Education Level
8         Mjob  Feature  Categorical       Occupation
9         Fjob  Feature  Categorical       Occupation
10      reason  Feature  Categorical             None
11    guardian  Feature  Categorical             None
12  traveltime  Feature      Integer             None
13   studytime  Feature      Integer             None
14    failures  Feature      Integer             None
15   schoolsup  Feature       Binary             None
16      famsup  Feature       Binary             None
17        paid  Feature       Binary             None
18  activities  Feature       Binary             None
19     nursery  Feature       Binary             None
20      higher  Feature       Binary             None
21    internet  Feature       Binary             None
22    romantic  Feature       Binary             None
23      famrel  Feature      Integer             None
24    freetime  Feature      Integer             None
25       goout  Feature      Integer             None
26        Dalc  Feature      Integer             None
27        Walc  Feature      Integer             None
28      health  Feature      Integer             None
29    absences  Feature      Integer             None
30          G1   Target  Categorical             None
31          G2   Target  Categorical             None
32          G3   Target      Integer             None

                                          description units missing_values
0   student's school (binary: 'GP' - Gabriel Perei...  None             no
1   student's sex (binary: 'F' - female or 'M' - m...  None             no
2              student's age (numeric: from 15 to 22)  None             no
3   student's home address type (binary: 'U' - urb...  None             no
4   family size (binary: 'LE3' - less or equal to ...  None             no
5   parent's cohabitation status (binary: 'T' - li...  None             no
6   mother's education (numeric: 0 - none,  1 - pr...  None             no
7   father's education (numeric: 0 - none,  1 - pr...  None             no
8   mother's job (nominal: 'teacher', 'health' car...  None             no
9   father's job (nominal: 'teacher', 'health' car...  None             no
10  reason to choose this school (nominal: close t...  None             no
11  student's guardian (nominal: 'mother', 'father...  None             no
12  home to school travel time (numeric: 1 - <15 m...  None             no
13  weekly study time (numeric: 1 - <2 hours, 2 - ...  None             no
14  number of past class failures (numeric: n if 1...  None             no
15      extra educational support (binary: yes or no)  None             no
16     family educational support (binary: yes or no)  None             no
17  extra paid classes within the course subject (...  None             no
18    extra-curricular activities (binary: yes or no)  None             no
19        attended nursery school (binary: yes or no)  None             no
20  wants to take higher education (binary: yes or...  None             no
21        Internet access at home (binary: yes or no)  None             no
22   with a romantic relationship (binary: yes or no)  None             no
23  quality of family relationships (numeric: from...  None             no
24  free time after school (numeric: from 1 - very...  None             no
25  going out with friends (numeric: from 1 - very...  None             no
26  workday alcohol consumption (numeric: from 1 -...  None             no
27  weekend alcohol consumption (numeric: from 1 -...  None             no
28  current health status (numeric: from 1 - very ...  None             no
29  number of school absences (numeric: from 0 to 93)  None             no
30         first period grade (numeric: from 0 to 20)  None             no
31        second period grade (numeric: from 0 to 20)  None             no
32  final grade (numeric: from 0 to 20, output tar...  None             no

In [ ]:
print("Filas y columnas:", df.shape)
df.info()

Filas y columnas: (649, 33)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), object(17)
memory usage: 167.4+ KB

In [ ]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
mean,16.744222,2.514638,2.306626,1.568567,1.930663,0.221880,3.930663,3.180277,3.184900,1.502311,2.280431,3.536210,3.659476,11.399076,11.570108,11.906009
std,1.218138,1.134552,1.099931,0.748660,0.829510,0.593235,0.955717,1.051093,1.175766,0.924834,1.284380,1.446259,4.640759,2.745265,2.913639,3.230656
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,16.000000,2.000000,1.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,2.000000,0.000000,10.000000,10.000000,10.000000
50%,17.000000,2.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,2.000000,11.000000,11.000000,12.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,32.000000,19.000000,19.000000,19.000000

In [ ]:
df.isna().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64